### PR TITLE
Refactored into class

### LINKED ISSUE #20: Create a class for robot moving
You should to move the code from orm_one_ros.py to the class that will be into this file or another one.

### PR DESCRIPTION
**Pull request by sw1pr0g**

### CODE REVIEW

**Comment by sw1pr0g** [comment]
@Kropanov need to test it with usb device

**Review by Kropanov — COMMENTED** [review]
@sw1pr0g Need to fix an error

**Comment by sw1pr0g** [comment]
@Kropanov error fixed, please check

**Review by Kropanov — COMMENTED** [review]
@sw1pr0g it still doesn't work

**Pull request closed without merging**
